name: Create new repo
description: 'Use #issueops to create a new repo in this org'
title: Create new repo
labels: issueops
assignees:
- KevinMSampson
body:
- type: input
  id: repo-name
  attributes:
    label: Repo name
    description: "Name of the new repo"
    placeholder: "Example: test-#"
  validations:
    required: true
- type: dropdown
  id: visibility
  attributes:
    label: Visibility
    description: What is the repo's visibility?
    multiple: false
    options:
      - public
      - private
#       - internal
  validations:
    required: true
- type: checkboxes
  id: 
  attributes:
    label: Code of Conduct
    description: By checking this and creating the issue, you agree not to abuse the test automation available here.
    options:
      - label: I agree to follow this project's Code of Conduct
        required: true
